language: c

sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "3Njik+f5HM4VM6wdu09NWR1cEFvNViTyK7+k1BFcO9v0i+ILJmuIkkhjyE79ou8+rKZzGjP9bNk8VcB8P/6dLg60IO7we6t+D8ibe4uS/zHRoxHmc88Uz3Khs7yUlDeUfCo6XgHwSCLJ1QHhR7XjkP7IVdQZwH4KKycl7GuYgZ0="

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi

os:
  - linux
  - osx

addons:
  coverity_scan:
    project:
      name: "cortoproject/corto"
      description: "Build submitted via Travis CI"
    notification_email: sander.mertens8@gmail.com
    build_command:
     - cd corto
     - rake
     - cd ..
    branch_pattern: coverity_scan

install:
  - cd ..
  - mkdir projects
  - mv corto projects/corto
  - cd projects
  - git clone https://github.com/cortoproject/c-binding.git
  - git clone https://github.com/cortoproject/xml.git
  - git clone https://github.com/cortoproject/corto-language.git
  - git clone https://github.com/cortoproject/io.git
  - git clone https://github.com/cortoproject/cortodoc.git
  - git clone https://github.com/cortoproject/test.git
  - git clone https://github.com/cortoproject/json.git
  - git clone https://github.com/cortoproject/t.git
  - git clone https://github.com/cortoproject/web.git
  - git clone https://github.com/cortoproject/admin.git
  - git clone https://github.com/cortoproject/examples.git
  - |+
    echo 'COMPONENTS = %w(corto c-binding json xml corto-language io cortodoc test t web admin)
    require "#{ENV["CORTO_BUILD"]}/forward"' > rakefile
  - source corto/configure
  - function hashes() { for g in `find . -name .git` ; do d=$(basename $(dirname $g)); h=$(git --git-dir $g rev-parse HEAD) ; echo -e "$d\t$h"; done } ; hashes | column -t | sort

script:
  - source corto/configure
  - rake
  - rake test
  # Test examples
  - cd examples
  - ./run.sh
  - cd ..
