language: c

sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "lrQtWGv7FRGEqOn/wdv0I4LePuWaCyJ4tSiLkYKh0RqQJ4oe5jsPN30lRskXMzeOBVK3HZefsnYE8+SDRezQCqaxFkjdHJv1fIqpl0D9+YYHAYXE12DUlXivgG/ujzGg2t33V05am+/oSWp3RCdJQYA1GhKP5tAU4535yS8roZI="

addons:
  coverity_scan:
    project:
      name: "Seldomberry/Corto"
      description: "Build submitted via Travis CI"
    notification_email: sander.mertens8@gmail.com
    build_command_prepend: "source configure"
    build_command:   "rake"
    branch_pattern: coverity_scan

before_install:

install:
  - cd ..
  - mkdir projects
  - mv corto projects/corto
  - cd projects
  - git clone https://github.com/cortoproject/c-binding.git
  - git clone https://github.com/cortoproject/xml.git
  - git clone https://github.com/cortoproject/corto-language.git
  - git clone https://github.com/cortoproject/io.git
  - git clone https://github.com/cortoproject/cortodoc.git
  - git clone https://github.com/cortoproject/test.git
  - git clone https://github.com/cortoproject/json.git
  - git clone https://github.com/cortoproject/examples.git
  - |+
    echo 'COMPONENTS = %w(corto c-binding xml corto-language io cortodoc test json)
    require "#{ENV["CORTO_BUILD"]}/forward"' > rakefile

script:
  - source corto/configure
  - rake
  - rake test
  # Test examples
  - cd examples
  - corto run Crud
  - corto run DynamicType
  - corto run HelloWorld
  - corto run Notifications
  - corto run Select
  - cd ..
